matrix:
  include:
    - language: php
      name: "API Unit Testing"
      php: 7.4
      services:
        - mysql
      cache:
        directories:
            - vendor
            - $HOME/.composer/cache
      before_script:
        - cp .env.ci .env
        - cp phpunit.xml.test phpunit.xml
        - touch database/database.sqlite
        - composer self-update
        - composer install --no-interaction
        - php artisan key:generate
        - php artisan migrate
      script: composer run test
    - language: php
      name: "Vue App E2E & Unit Testing"
      env:
        - TEST_DIR=vue_app
      php: 7.4
      services:
        - mysql
      cache:
        yarn: false
        directories:
            #- vue_app/node_modules
            - vendor
            - $HOME/.composer/cache
            #- $HOME/.cache/Cypress
      before_script:
        - cp .env.ci .env
        - cp phpunit.xml.test phpunit.xml
        - touch database/database.sqlite
        - composer self-update
        - composer install --no-interaction
        - php artisan key:generate
        - php artisan migrate
        - php artisan serve & APP_PID=$!
        - nvm install stable
        - curl -s localhost:8000/api/ping
        - cd $TEST_DIR && yarn
      script:
        - yarn test:unit
        - yarn test:e2e-ci
      after_script:
        - kill $APP_PID
    
    
