matrix:
  include:
    - language: php
      php: 7.4
      before_script:
        - cp .env.ci .env
        - touch storage/database.sqlite
        - composer self-update
        - composer install --no-interaction
        - php artisan key:generate
        - php artisan migrate --database=sqlite
      script: composer run test
    #- language: node_js
    #  node_js: "13"
