matrix:
  include:
    - language: php
      php: 7.4
      before_script:
        - cp .env.ci .env
        - cp phpunit.xml.test phpunit.xml
        - touch database/database.sqlite
        - composer self-update
        - composer install --no-interaction
        - php artisan key:generate
        - php artisan migrate
      script: composer run test
    - language: php
      cache:
        directories:
            - vue_app/node_modules
            - vendor
            - $HOME/.composer/cache
      php: 7.4
      env:
        - TEST_DIR=vue_app
      before_script:
        - cp .env.ci .env
        - cp phpunit.xml.test phpunit.xml
        - touch database/database.sqlite
        - composer self-update
        - composer install --no-interaction
        - php artisan key:generate
        - php artisan migrate
        - php artisan serve & APP_PID=$!
        - nvm install stable
        - yarn -v
        - npm install npm@latest -g
        - cd $TEST_DIR && npm install
      script:
        - npm run test:unit
        - npm run test:e2e-ci
      after_script:
        - kill $APP_PID
    
    
