name: Downstream CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deployment:
    name: Deploy
    # environment: prod
    runs-on: ubuntu-latest
    needs: api-unit-test
    continue-on-error: true
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Trigger Downstream API Build
        run: |
          /usr/bin/curl --output /dev/null --silent -H "Content-Type: application/json" -X POST "${{ secrets.DOCKER_HUB_API_TRIGGER_ROUTE }}"
      - name: Trigger Downstream App Build
        run: |
          /usr/bin/curl --output /dev/null --silent -H "Content-Type: application/json" -X POST "${{ secrets.DOCKER_HUB_APP_TRIGGER_ROUTE }}"
      - name: Get Latest Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}
      - name: Sentry Release
        uses: getsentry/action-release@v1.1.6
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: prod
          version: ${{ github.sha }}

  api-unit-test:
    name: Laravel API Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 8989:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      #- name: Set Directory Permissions
      #  run: chmod -R 777 storage bootstrap/cache
      #- name: Run Database Migrations
      #  run: php artisan migrate
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit --exclude-group youtube
        env:
          YOUTUBE_KEY: ${{ secrets.YOUTUBE_KEY }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  #vue-app-tests:
  #  name: Vue App Tests
  #  runs-on: ubuntu-latest
  #  needs: api-unit-test
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: Setup Node v16.14.0
  #      uses: actions/setup-node@v1
  #      with:
  #        node-version: v16.14.0
  #    - name: Yarn Install
  #      working-directory: vue_app
  #      run: yarn install
  #    - name: Build Vue App
  #      working-directory: vue_app
  #      run: yarn build
  #    - name: Run Unit Tests
  #      working-directory: vue_app
  #      run: yarn test:unit
